### ISSUE TITLE
Example Code not working

### ISSUE THREAD

**Issue by ScreamingHawk** [danielstern/cyo#8]
This project looks great as something I can make with my daughter, but I'm struggling to get it to work. 

The getting started guide has a dead link `<script src="https://raw.githubusercontent.com/danielstern/cyo/master/cyo.js"></script>`

But when replaced with a working link `<script src="https://raw.githubusercontent.com/danielstern/cyo/master/js/cyo.js"></script>` it still doesn't seem to work. 

My testing page is the `Getting Started` code snippet with the `Example` story code snippet for the body.

**Comment by ScreamingHawk** [comment]
Could be this: `Refused to execute script from 'https://raw.githubusercontent.com/danielstern/cyo/master/js/cyo.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.` Cloning the javascript to serve locally fixes the problem. 

Would be nice if you could update the `Getting Started` to reflect this. 

Thanks for the library! This is great

**Comment by ScreamingHawk** [comment]
You can use `https://rawgit.com/danielstern/cyo/master/js/cyo.js`. 

Sorry for the comment spam.

**Comment by danielstern** [comment]
Fixed now!

**Comment by andymeneely** [comment]
Is it fixed now? I'm just trying this out for the first time and I can't get the example code to work - same problem where I see everything all at once. I'm using the above script tag.

**Comment by darabandev** [comment]
@danielstern Thanks for the response! Still having the same problem, unfortunately.

**Comment by andymeneely** [comment]
I think I got it! You need `ng-app="cyo"` in the `body` tag.

**Comment by ScreamingHawk** [comment]
I've added a pull request to update the documentation based on @andymeneely comment about the `body` tag. 

Would be nice to have a minimal complete stand-alone example in the future. I remember this took me a bit to figure out when I used it 6+ months ago too. 

Thanks again for the project!
